from keyword import softkwlist
from pygeopkg.core.geopkg import GeoPackage
from pygeopkg.core.srs import SRS
from pygeopkg.core.field import Field
from pygeopkg.shared.enumeration import GeometryType, SQLFieldTypes


GeMS_basic_feature_class_fields = {
    """Required features classes and tables:"""
    
    "MapUnitPolys": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('MApUnitPolys_ID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        ),

    "ContactsAndFaults": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('IsConcealed', SQLFieldTypes.text, 1),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ExistenceConfidence', SQLFieldTypes.text, 50),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('ContactsAndFaults_ID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
    ),

    "MapUnitOverlayLines": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('IsConcealed', SQLFieldTypes.text, 1),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ExistenceConfidence', SQLFieldTypes.text, 50),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('MapUnitOverlayLines_ID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
    ),

    "DescriptionOfMapUnits": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Name', SQLFieldTypes.text, 254),
        Field('FullName', SQLFieldTypes.text, 254),
        Field('Age', SQLFieldTypes.text, 254),
        Field('Description', SQLFieldTypes.text, 3000),
        Field('HierarchyKey', SQLFieldTypes.text, 254),
        Field('ParagraphStyle', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 30),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('AreaFillRGB', SQLFieldTypes.text, 254),
        Field('AreaFillPatternDescription', SQLFieldTypes.text, 254),
        Field('DescriptionSourceID', SQLFieldTypes.text, 50),
        Field('GeoMaterial', SQLFieldTypes.text, 254),
        Field('GeoMaterialConfidence', SQLFieldTypes.text, 254),
        Field('MapUnitOverlayLines_ID', SQLFieldTypes.text, 50),
    ),

    "DataSources": (
        Field('Source', SQLFieldTypes.text, 500),
        Field('Notes', SQLFieldTypes.text, 300),
        Field('URL', SQLFieldTypes.text, 300),
        Field('DataSources_ID', SQLFieldTypes.text, 50),
    ),

    "Glossary": (
        Field('Term', SQLFieldTypes.text, 254),
        Field('Definition', SQLFieldTypes.text, 3000),
        Field('DefinitionSourceID', SQLFieldTypes.text, 50),
        Field('Glossary_ID', SQLFieldTypes.text, 50),
    ),

    """As-needed tables and feature classes"""

    "GenericPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('GenericPoints_ID', SQLFieldTypes.text, 50),
    ),

    "GenericSamples": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('FieldSampleID', SQLFieldTypes.text, 254),
        Field('AlternateSampleID', SQLFieldTypes.text, 254),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('GenericSamples_ID', SQLFieldTypes.text, 50),
    ),

    "OrientationPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Azimuth', SQLFieldTypes.integer),
        Field('Inclination', SQLFieldTypes.integer),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('OrientationConfidenceDegrees', SQLFieldTypes.integer),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('OrientationSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('OrientationPoints_ID', SQLFieldTypes.text, 50),
    ),

    "GeochronPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('FieldSampleID', SQLFieldTypes.text, 254),
        Field('AlternateSampleID', SQLFieldTypes.text, 254),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('MAterialAnalyzed', SQLFieldTypes.text, 254),
        Field('NumericAge', SQLFieldTypes.double), # the GeMS definition says this field should be a single (integer), but that limits entries and rounds them, which does not properly preserve data
        Field('AgePlusError', SQLFieldTypes.double), # the GeMS definition says this field should be a single (integer), but that limits entries and rounds them, which does not properly preserve data
        Field('AgeMinusError', SQLFieldTypes.double), # the GeMS definition says this field should be a single (integer), but that limits entries and rounds them, which does not properly preserve data
        Field('ErrorMeasure', SQLFieldTypes.text, 254),
        Field('AgeUnits', SQLFieldTypes.text, 50),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('AnalysisSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('GeochronPoints_ID', SQLFieldTypes.text, 50),
    ),

    "GeochemPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('StationsID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('GeochemPoints_ID', SQLFieldTypes.text, 50),
        Field('SiO2', SQLFieldTypes.text, 50),
        Field('Al2O3', SQLFieldTypes.text, 50),
        Field('Fe2O3', SQLFieldTypes.text, 50),
        Field('CaO', SQLFieldTypes.text, 50),
        Field('MgO', SQLFieldTypes.text, 50),
        Field('Na2O', SQLFieldTypes.text, 50),
        Field('K20', SQLFieldTypes.text, 50),
        Field('Cr2O3', SQLFieldTypes.text, 50),
        Field('TiO2', SQLFieldTypes.text, 50),
        Field('MnO', SQLFieldTypes.text, 50),
        Field('P2O5', SQLFieldTypes.text, 50),
        Field('Sro', SQLFieldTypes.text, 50),
        Field('BaO', SQLFieldTypes.text, 50),
        Field('LOI', SQLFieldTypes.text, 50),
        Field('SiO2', SQLFieldTypes.text, 50),
        Field('Total', SQLFieldTypes.text, 50),
        Field('C', SQLFieldTypes.text, 50),
        Field('S', SQLFieldTypes.text, 50),
        Field('Ba', SQLFieldTypes.text, 50),
        Field('Ce', SQLFieldTypes.text, 50),
        Field('Cr', SQLFieldTypes.text, 50),
        Field('Cs', SQLFieldTypes.text, 50),
        Field('Dy', SQLFieldTypes.text, 50),
        Field('Er', SQLFieldTypes.text, 50),
        Field('Eu', SQLFieldTypes.text, 50),
        Field('Ga', SQLFieldTypes.text, 50),
        Field('Gd', SQLFieldTypes.text, 50),
        Field('Ge', SQLFieldTypes.text, 50),
        Field('Hf', SQLFieldTypes.text, 50),
        Field('Ho', SQLFieldTypes.text, 50),
        Field('La', SQLFieldTypes.text, 50),
        Field('Lu', SQLFieldTypes.text, 50),
        Field('Nb', SQLFieldTypes.text, 50),
        Field('Nd', SQLFieldTypes.text, 50),
        Field('Pr', SQLFieldTypes.text, 50),
        Field('Rb', SQLFieldTypes.text, 50),
        Field('Sm', SQLFieldTypes.text, 50),
        Field('Sn', SQLFieldTypes.text, 50),
        Field('Sr', SQLFieldTypes.text, 50),
        Field('Ta', SQLFieldTypes.text, 50),
        Field('Tb', SQLFieldTypes.text, 50),
        Field('Th', SQLFieldTypes.text, 50),
        Field('Tm', SQLFieldTypes.text, 50),
        Field('U', SQLFieldTypes.text, 50),
        Field('V', SQLFieldTypes.text, 50),
        Field('W', SQLFieldTypes.text, 50),
        Field('Y', SQLFieldTypes.text, 50),
        Field('Yb', SQLFieldTypes.text, 50),
        Field('Zr', SQLFieldTypes.text, 50),
        Field('As_', SQLFieldTypes.text, 50),
        Field('Bi', SQLFieldTypes.text, 50),
        Field('Hg', SQLFieldTypes.text, 50),
        Field('In_', SQLFieldTypes.text, 50),
        Field('Re', SQLFieldTypes.text, 50),
        Field('Sb', SQLFieldTypes.text, 50),
        Field('Se', SQLFieldTypes.text, 50),
        Field('Te', SQLFieldTypes.text, 50),
        Field('Tl', SQLFieldTypes.text, 50),
        Field('Ag', SQLFieldTypes.text, 50),
        Field('Cd', SQLFieldTypes.text, 50),
        Field('Co', SQLFieldTypes.text, 50),
        Field('Cu', SQLFieldTypes.text, 50),
        Field('Li', SQLFieldTypes.text, 50),
        Field('Mo', SQLFieldTypes.text, 50),
        Field('Ni', SQLFieldTypes.text, 50),
        Field('Pb', SQLFieldTypes.text, 50),
        Field('Sc', SQLFieldTypes.text, 50),
        Field('Zn', SQLFieldTypes.text, 50),

    ),

    "Stations": (
        Field('FieldID', SQLFieldTypes.text, 50),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ObservedMapUnit', SQLFieldTypes.text, 10),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('LocationMethod', SQLFieldTypes.text, 254),
        Field('TimeDate', SQLFieldTypes.date),
        Field('Observer', SQLFieldTypes.text, 254),
        Field('SignificantDimensionMeters', SQLFieldTypes.integer),
        Field('GPSX', SQLFieldTypes.double),
        Field('GPSY', SQLFieldTypes.double),
        Field('PDOP', SQLFieldTypes.integer),
        Field('MapX', SQLFieldTypes.double),
        Field('MapY', SQLFieldTypes.double),
        Field('Stations_ID', SQLFieldTypes.text, 50),
    ),

    "GeologicLines": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('IsConcealed', SQLFieldTypes.text, 1),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ExistenceConfidence', SQLFieldTypes.text, 50),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('GeologicLines_ID', SQLFieldTypes.text, 50),
    ),

    "CartographicLines": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('CartographicLines_ID', SQLFieldTypes.text, 50),
    ),

    "IsoValueLines": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Value', SQLFieldTypes.integer),
        Field('ValueConfidence', SQLFieldTypes.integer),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('IsoValueLines_ID', SQLFieldTypes.text, 50),
    ),

    "MapUnitLines": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('IsConcealed', SQLFieldTypes.text, 1),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ExistenceConfidence', SQLFieldTypes.text, 50),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('MapUnitLines_ID', SQLFieldTypes.text, 50),
    ),

    "MapUnitPoints": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('ExistenceConfidence', SQLFieldTypes.text, 50),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('MapUnitPoints_ID', SQLFieldTypes.text, 50),
    ),

    "MapUnitOverlayPolys": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('MapUnitOverlayPolys_ID', SQLFieldTypes.text, 50),
    ),

    "OverlayPolys": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('IdentityConfidence', SQLFieldTypes.text, 50),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('OverlayPolys_ID', SQLFieldTypes.text, 50),
    ),

    "DataSourcePolys": (
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('DataSourcePolys_ID', SQLFieldTypes.text, 50),
    ),

    "RepurposedSymbols": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('RepurposedSymbols_ID', SQLFieldTypes.text, 50),
    ),

    """Optional features classes and tables as described in GeMS specs"""

    "CMUMapUnitPolys": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('CMUMapUnitPolys_ID', SQLFieldTypes.text, 50),
    ),

    "CMULines": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('CMULines_ID', SQLFieldTypes.text, 50),
    ),

    "CMUPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('CMUPoints_ID', SQLFieldTypes.text, 50),
    ),

    "MiscellaneousMapInformation": (
        Field('MapProperty', SQLFieldTypes.text, 254),
        Field('MapPropertyValue', SQLFieldTypes.text, 3000),
        Field('MiscellaneousMapInformation_ID', SQLFieldTypes.text, 50),
    ),

    "LayerList": (
        Field('OrderFromTop', SQLFieldTypes.integer),
        Field('FeatureDataSetName', SQLFieldTypes.text, 254),
        Field('ElevationObject', SQLFieldTypes.text, 254),
        Field('Description', SQLFieldTypes.text, 3000),
        Field('LayerList_ID', SQLFieldTypes.text, 50),
    ),

    "StandardLithology": (
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('PartType', SQLFieldTypes.text, 254),
        Field('Lithology', SQLFieldTypes.text, 254),
        Field('ProportionTerm', SQLFieldTypes.text, 254),
        Field('ProportionValue', SQLFieldTypes.integer),
        Field('ScientificDonfidence', SQLFieldTypes.text, 254),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('StandardLithology_ID', SQLFieldTypes.text, 50),
    ),

    """Optional feature classes not described in GeMS specs"""

    "FossilPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('FieldSampleID', SQLFieldTypes.text, 254),
        Field('AlternateSampleID', SQLFieldTypes.text, 254),
        Field('MaterialAnalyzed', SQLFieldTypes.text, 254),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('FossilForms', SQLFieldTypes.text, 3000),
        Field('FossilAge', SQLFieldTypes.text, 254),
        Field('LocationSourceID', SQLFieldTypes.text, 50),
        Field('FossilFormsSourceID', SQLFieldTypes.text, 50),
        Field('FossilAgeSourceID', SQLFieldTypes.text, 50),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('FossilPoints_ID', SQLFieldTypes.text, 50),
    ),

    "PhotoPoints": (
        Field('Type', SQLFieldTypes.text, 254),
        Field('StationID', SQLFieldTypes.text, 50),
        Field('MapUnit', SQLFieldTypes.text, 10),
        Field('Label', SQLFieldTypes.text, 50),
        Field('Symbol', SQLFieldTypes.text, 254),
        Field('PlotAtScale', SQLFieldTypes.integer),
        Field('LocationConfidenceMeters', SQLFieldTypes.integer),
        Field('DataSourceID', SQLFieldTypes.text, 50),
        Field('PhotoID', SQLFieldTypes.text, 50),
        Field('PhotoSubject', SQLFieldTypes.text, 254),
        Field('ViewDirection', SQLFieldTypes.text, 254),
        Field('ViewWidth', SQLFieldTypes.text, 254),
        Field('Notes', SQLFieldTypes.text, 254),
        Field('PhotoPoints_ID', SQLFieldTypes.text, 50),
    )
}